apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: cakephp-mysql-persistent
    openshift.io/deployment.name: cakephp-mysql-persistent-1
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: cakephp-mysql-persistent-1-
  labels:
    deployment: cakephp-mysql-persistent-1
    deploymentconfig: cakephp-mysql-persistent
    name: cakephp-mysql-persistent
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: cakephp-mysql-persistent-1
    uid: 5a73c917-27aa-11e9-9ce7-525400ea2b36
spec:
  containers:
  - env:
    - name: DATABASE_SERVICE_NAME
      value: mysql
    - name: DATABASE_ENGINE
      value: mysql
    - name: DATABASE_NAME
      value: default
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: cakephp-mysql-persistent
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: cakephp-mysql-persistent
    - name: CAKEPHP_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          key: cakephp-secret-token
          name: cakephp-mysql-persistent
    - name: CAKEPHP_SECURITY_SALT
      valueFrom:
        secretKeyRef:
          key: cakephp-security-salt
          name: cakephp-mysql-persistent
    - name: OPCACHE_REVALIDATE_FREQ
      value: "2"
    image: 172.30.1.1:5000/question4/cakephp-mysql-persistent@sha256:22dccfa498871e6ed7860866a0d09964877b565647eeb5d8f3a106fe9436a290
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health.php
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 3
    name: cakephp-mysql-persistent
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health.php
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000200000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ft7cc
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-hvdgb
  nodeName: localhost
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000200000
    seLinuxOptions:
      level: s0:c14,c9
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-ft7cc
    secret:
      defaultMode: 420
      secretName: default-token-ft7cc
status:
  phase: Pending
  qosClass: Burstable
