apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.name: mysql
    openshift.io/deployment.name: mysql-1
    openshift.io/scc: restricted
  creationTimestamp: null
  labels:
    openshift.io/deployer-pod-for.name: mysql-1
  name: mysql-1-deploy
  ownerReferences:
  - apiVersion: v1
    kind: ReplicationController
    name: mysql-1
    uid: 3663da0e-27a6-11e9-9ce7-525400ea2b36
spec:
  activeDeadlineSeconds: 21600
  containers:
  - env:
    - name: OPENSHIFT_DEPLOYMENT_NAME
      value: mysql-1
    - name: OPENSHIFT_DEPLOYMENT_NAMESPACE
      value: question4
    image: openshift/origin-deployer:v3.11.0
    imagePullPolicy: IfNotPresent
    name: deployment
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000200000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployer-token-8kfgf
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: deployer-dockercfg-dllvw
  nodeName: localhost
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000200000
    seLinuxOptions:
      level: s0:c14,c9
  serviceAccount: deployer
  serviceAccountName: deployer
  terminationGracePeriodSeconds: 10
  volumes:
  - name: deployer-token-8kfgf
    secret:
      defaultMode: 420
      secretName: deployer-token-8kfgf
status:
  phase: Pending
  qosClass: BestEffort
