apiVersion: v1
kind: Pod
metadata:
  name: question3-2
spec:
  containers:
  - name: question3-2
    image: alpine
    volumeMounts:
    - name: vol
      mountPath: /opt/data
  volumes:
  - name: vol
    emptyDir: {}
