apiVersion: batch/v1
kind: Job
metadata:
  name: paralleljobs
spec:
  parallelism: 4    
  completions: 4
  replicas: 4  
  template:         
    metadata:
      name: pi
    spec:
      containers:
      - name: cont1
        image: alpine
        command: ["/bin/sh","-c"]
        args: ["echo 'This is parallel'"]
      restartPolicy: OnFailure 
